### PR TITLE
bugfix(validator): switch from string to array of string

### LINKED ISSUE #54: `file` type definition does not match swagger spec
The following block of code indicates that consumes should be a string.
```
                consumes: {
                    type: 'string',
                    pattern: /multipart\/form-data|application\/x-www-form-urlencoded/,
                    required: true
                },
```

The swagger spec (2.0) shows that consumes is a list of strings.

```
consumes	[string]	A list of MIME types the operation can consume. This overrides the consumes definition at the Swagger Object. An empty value MAY be used to clear the global definition. Value MUST be as described under Mime Types.
```

### PR DESCRIPTION
**Pull request by kenjones-cisco**
Update the `consumes` of file type to be array with items being a string with pattern.

closes #54

### CODE REVIEW

**Comment by tlivings** [comment]
Is there a situation where you'd have more than one content-type header?

**Comment by kenjones-cisco** [comment]
No, but to align to the swagger spec, so that writing the API definition following the swagger spec expects the definition to be a list. It causes an error in Swagger Editor.

**Comment by tlivings** [comment]
Cool. I think reviewing this has actually revealed a gaping hole in the validation of `file` type :(

**Comment by subeeshcbabu** [comment]
lgtm :+1:

**Pull request merged**
