### PR TITLE
fix for #76, replaces #79

### PR DESCRIPTION
**Pull request by tlivings**

### CODE REVIEW

**Comment by anchnk** [comment]
The PR looks fine however current master build is broken due to linting issue. That should be fixed before new PR could be merged in the project.

**Comment by tlivings** [comment]
Yes, it's jshint and needs the rule changed. I'm fine with the increased cyclomatic complexity.

**Comment by anchnk** [comment]
Perfect. Thanks a lot.
Next step is merging the PR and publish a new npm release so that we can update dependencies in our project

**Comment by subeeshcbabu** [comment]
Published `swaggerize-routes@1.0.11`

**Pull request merged**
