### PR TITLE
Support for config, cache, jsonp and json option parameters

### PR DESCRIPTION
**Pull request by FGRibreau**
This PR allows the support of hapi plugins like [mrhorse](https://github.com/mark-bradshaw/mrhorse) etc...

### CODE REVIEW

**Comment by MarcFRICOU** [comment]
:+1:

**Comment by jcare44** [comment]
:+1: really need this !

**Comment by tlivings** [comment]
Looks good to me!

**Comment by subeeshcbabu** [comment]
@tlivings - Can this be merged?

**Pull request merged**
